textList = [
    "    De prime a bord, nous devons",
    "souliqner que l'appellation tapis",
    "Médiouna (Photo3) recourt davantage",
    "a une réalité historique plutat quia",
    "un constat de fait. Cévolution des",
    "chases fait quiil serait plus",
    "significatif et plus cohérent de",
    "parler des tapis de Casablanca ou",
    "d'utiliser un compasé tapis de",
    "Médiouna-casablanca. Autrement, la",
    "référence au milieu géographique et",
    "au lieu de la production serait",
    "impropre. Des conditions",
    "géographiques, historiques,",
    "écanarniques et culturelles du tapis",
    "conditionnent son histoire, ainsi que",
    "son évolution.",
    " ",
    "    L'appellation tapis de Médiouna",
    "peut etre ramenée a un contexte",
    "plutot d'ordre commercial que d'ordre",
    "ethnique ou culturel. Cette",
    "appellation a été tres employée par",
    "les commercants, et par Ia suite le",
    "qualificatif est devenu cornrnunérnent",
    "employé a Ia fois par les",
    "professionnels et les consommateurs",
    "de tapis, En dépit des controverses",
    "relatives a son appellation, le tapis",
    "de Médiouna est considéré par",
    "excellence comme un tapis citadin; il",
    "s'est identifié par ses motifs, ses",
    "coloris, et sa composition, Ce tapis",
    "possade les mêmes degrés de finesse",
    "que celui de Rabat. II comprend presque",
    "les memes qualités de serrage et de",
    "nouage. Certains motifs de décoration",
    "utilisés dans la confection des tapis",
    "de Rabat sont meme empruntés au tapis",
    "de Médiouna.",
    " ",
    "    La tradition de tissage dans la",
    "région de Médiouna puise, sans aucun",
    "doute, son substrat culturel dans un",
    "fond civilisationnel tres ancien et",
    "tres diversifié.",
    " ",
    "    Des survivances de ce substrat",
    "devaient continuer jusqu'aux temps",
    "modernes. Niayant pas rompu ses liens",
    "socio-économiques, religieux et",
    "affectifs avec le milieu rural",
    "diorigine, la tisseuse des quartiers",
    "périphériques de Casablanca, Médiouna",
    "continuait, dans une certaine mesure,",
    "de vivre selon un mode de vie",
    "semi-nomade. Se déplaçant diune",
    "maniére saisonniere de la ville a la",
    "campagne, soit pour participer aux",
    "différentes manifestations rurales,",
    "moussems annuels, célébrant le culte",
    "des «saints» de la région, mariages,",
    "moissons.... soit simplement pour",
    "s'approvisionner en produits",
    "agricales et en Iaine, Un autre",
    "caurant culturel qui aurait surement",
    "imprégné la tradition de tissage de",
    "Médiouna proviendrait du contact de",
    "la région de la Chaouia avec les",
    "voies traditionnelles du commerce",
    "intérieur et maritime reliant les",
    "cités anciennes du litoral atlantique",
    "selon un axe allant de Rabat/Salé en",
    "passant par Anfa et arrivant a Safi.",
]