textList = [
   "   A travers l'histoire, les marocains ont été toujours portés, de par",
   "leur nature rêveuse et contemplative, à s'exprimer dans des formes",
   "d'art spontanées. Ils ont conservé, à travers les bouleversements",
   "successifs d'une histoire mouvementée, beaucoup de leurs qualités",
   "primitives, qui se manifestent dans les arts manuels de façon souvent",
   "insurpassable, Les ceuvres exposées dans les divers musées à travers",
   "le Maroc laissent découvrir un art qui puise son origine dans le",
   "comportement quotidien, et s'inspire d'une conception purement",
   "spontanée de la vie sociale et patfois théocratique, dans laquelle se",
   "confondent le divin et l'humain.",
   " ",
   "   Dans l'expression de l'âme marocaine, l'art du tapis demeure l'un",
   "des témoignages les plus privilégiés et les plus authentiques de la",
   "recherche du beau. II serait très prétentieux d'essayer de fixer la",
   "date de l'apparition des tapis au Maroc, car celle-ci est considérée",
   "comme une évolution du tissage, dont les origines remontent",
   "indéniablement à la préhistoire. Si des historiens attribuent",
   "l'apparition du tissage aux Eqyptiens, aux Indous, aux Assyriens, Aux",
   "Incas... le plus plausible est que cet art tradition est apparu dans",
   "une même époque et dans des endroits différents du globe. On ne peut",
   "supposer alors qu'une chose, c'est que l'histoire du tissage est aussi",
   "ancienne que l'histoire du Maroc même.",
   "",
   "   Ibn Khaldoun, dans ses prolégomènes, rédigés à la fin du quatorzième",
   "siècle, évoque maintes fois dans l'esprit particulier au monde",
   "islamique, les métiers qui se pratiquaient en son temps, notamment le",
   "tissage d'étoffe qu'il traite en cinq lignes sans faire la moindre",
   "allusion au tapis. Serait-ce que les villes ignoraient ce genre de",
   "fabrication? Serait-ce parce que le cloisonnement des centres",
   "commerciaux et les difficultés de transport empêchaient la diffusion",
   "du tapis?",
   " ",
   "   On peut dire avec précaution également que l'artisanat tribal, en",
   "général, n'attirait pas l'attention des historiens.",
   " "
   "   De toutes les façons, aucun des auteurs, même les plus connus qui",
   "ont écrit sur l'histoire du Maroc, notamment AI Murrakoshi dans Al",
   "Mouâjib, Ibn Abi Zirâ dans Rawd AI Kirtas, AI Egzennay dans Zahrat",
   "AI As ou l'auteur anonyme de la Dakirat Attaniya n'ont parlé du",
   "tapis, Et il est également possible que certains écrits soient perdus",
   "ou soient encore enfouis dans quelques bibliothèques.",
   " "
   "   Il faut attendre la fin du dix neuvième siècle et le début du",
   "vingtième pour que les littératures étrangeres (française, allemande",
   "et même anglaise) commencent à découvrir le tapis marocain, à en",
   "définir les différents genres, indiquer les lieux de production, sans",
   "aborder toutefois l'essentiel, à savoir son histoire. Il faut",
   "reconnaítre que la résistance berbère, à l'installation du protectorat,",
   "jusqu'en 1933, rendait toute recherche très délicate.",
   " ",
   "   Malgré cette abondance littéraire, des lacunes existent et de",
   "nombreuses questions restent sans réponse.",
   " ",
   "   Si l'origine du tapis citadin soulève encore des controverses,",
   "l'unanimité se fait autour du tapis bédouin en tant que tapis marocain",
   "authentique. Ceux de Rabat, Médiouna et Casablanca posent encore un",
   "certain nombre de questions.",
   " ",
   "   Alors que les deux derniers sont inspirés du tapis de Rabat, le",
   "livre Arts et objets du Maroc souligne, à propos d'un tapis de",
   "Médiouna, ..que les motifs et la composition du décor sont dans la",
   "plus pure tradition espagnole du seizième siècle. D'autres auteurs",
   "affirment que le tapis espagnol du 16ème siècle est inspiré de l'art",
   "arabe ou turco-persan.",
   " ",
   "   Quant au tapis r'bati, selon les uns, il serait venu d'Andalousie,",
   "parmi les souvenirs précieux emportés par les Gharnatis expulsés",
   "d'Espagne, à la fin du 15ème siècle et qui se sont fixés à Rabat, Fès",
   "et Tétouan. C'est la thèse que soutiennent les notables éclairés de",
   "Rabat, pour la plupart descendants authentiques des Gharnatis. Une",
   "telle position est justifiable si l'on tient compte de la proximité de",
   "la Péninsule Ibérique et des liens qui ont toujours uni les deux",
   "communautés.",
   " ",
   "   Mais d'après Prosper Ricard, qui se base sur la comparaison des",
   "tapis de Rabat avec ceux d'Asie Mineure (Anatolie et Perse) étudiés",
   "par des chercheurs allemands et anglais, et suite aux rapprochernents",
   "qu'il fait quant à l'encadrement, aux couleurs et même aux motifs,",
   "l'auteur du Corpus des Tapis Marocains soutient que le tapis de",
   "Rabat aurait été introduit au Maroc par les Turcs, au 18ème siècle,",
   "lors de leur occupation de l'Algérie.",
   " ",
   "   Quoi qu'il en soit, un fait est certain; le tapis se confectionnait",
   'déjà sur les bords du "Bouregreg" au 18ème siècle: un tapis dit de',
   "Chiadma porte la date tissée, 1202 hégirienne, soit1798 (photo a).",
   " ",
   "   Dans l'attente des résultats de la recherche, on ne trouve, pour le",
   "moment que cinq passages relatifs au tapis dont trois sont cités par",
   "P. Ricard:",
   " ",
   "   1) L'auteur du Corpus souligne dans Tapis marocains que l'histoire",
   "rappotte que le Sultan Moulay El Hassan, voulant remercier les chefs",
   "d'Etats européens de leurs félicitations à l'occasion de son accession",
   "au trone du Maroc, leur envoya une ambassade chargée de présents",
   "destinés au Président de la République française Mac Mahon, aux rois",
   "de Belgique et d'ltalie, Léopold Il et Victor Emmanuel II, ainsi qu'à",
   "la reine d'Angleterre Victoria. Les chefs d'Etats de ces pays reçurent,",
   "entre autres objets, chacun six tapis de Rabat, tandis que leurs Chefs",
   "de Gouvernement et leurs Ministres des Affaires Etrangères en reçurent",
   "deux chacun,",
   "",
   "   De son coté, Abou Abbes Naciri, dans son ouvrage AI Istiqssa, écrit",
   "à la fin du règne de Moulay El Hassan Premier et parle de présents",
   "offerts aux mêmes chefs d'Etat, Il cite la délégation qui les",
   "accompagna, présidée par l'ambassadeur Si Mohamed Ben Tahar Zebdi, de",
   "Rabat.",
   " ",
   "   2) Commentant un tapis de Rabat, Prosper Ricard écrit: Ce tapis fit",
   "partie jusqu'en 1907 du mobilier d'un membre de la famille chérifienne,",
   "Moulay Rachid, (cousin de l'ex-sultan Moulay Hafid). Il fut fabriqué,",
   "dit-on, vers 1858, sur ordre du sultan Moulay Abderrahmane (1822-1859),",
   "par les soins d'Al Adnani",
   " ",
   "   3) Le troisième point concerne la révélation de la date d'exécutio",
   "d'un tapis de Chiadma (ou de Rabat) : 1202 hégirienne, soit1798.",
   
   "   4) A propos du commerce marocain avec la France, durant les années",
   '1860-1866, Jean Louis Miège écrit : "La valeur des tissus de laine et',
   "des tapis exportés est de 350.000 à 55Cl.ClClCl francs par an. Un fort",
   'accroissement caractérise ces ventes en 1863".',
   " ",
   "   5) Quant à la cinquième citation, c'est Mohammed Ben Hassan AI",
   "Ouazzan, dit Léon l'Aricain qui écrit, au début du 16ème siècle,",
   "parlant de la Kissaria de Fès : Près de là, dans quelques petites",
   "boutiques, on vend aux enchères des tapis et des couvre-lits.",
   " ",
   "   L'industrie du tapis ne s'est guère développée a Fès, comme dans",
   "d'autres Villes malgré la présence de l'élément Gharnati.",
]