textList = [
    "    Par er u tapis de Fes (photo4)",
    "seralt, pour les uns, prétentieux et",
    "douteux peut-etre, mais pour d'autres,",
    "il serait justifié et cohérent avec",
    "un fait et une réalité qui se song",
    "imposés. Car, comment peut onirnaginer",
    "Fes sans tradition de tissage de",
    "tapis ? Par quoi étaient embellies",
    "les aires des fastidieuses demeures",
    "de cette ville ? Etait-il possible",
    "que les émigrants andalous auraient",
    "tout amené avec eux a rexception des",
    "tapis ? Auraient-ils oublié, dans la",
    "tentative de recréer le paradis perdu,",
    "d' accorder une place au tapis ? Et",
    "comment peut-on expliquer la",
    "contradiction, entre le décor ainsi",
    "trahi et le gout de Fes réputé des",
    "plus raffinés ? Et quien est-il advenu",
    "des traditions de tissage des tribus",
    "de la région qui ont, par vagues",
    "successives, peuplé la ville de Fes ?",
    " ",
    "    Faut-il rappeler encore que Fes",
    "fut, durant des siacles, un carrefour",
    "des civilisations et un centre de",
    "rayonnement intellectuel et",
    "commercial. Fes constituait le point",
    "de passage obligatoire sur I'axe",
    "routier reliant l'Est a 1'0uest",
    "(Tlemcen Fes Marrakech) et le Sud au",
    "Nord (Tombouctou Sijilmassa - Fes -",
    "Tétouan). Elle fut, également, la",
    "capitale politique et le lieu de",
    "séjour privilégie de plusieurs",
    "sultans.",
    " ",
    "    Toutefois, s'il est indéniable",
    "d'affirmer l'existence de tissage a",
    "Fes et notamment celui des tapis,",
    "reste a justifier l'emploi de",
    "l'attribut «tapis de Fes.",
    " ",
    "    Ceci nous amenera a parler des",
    "caractéristiques techniques et", 
    "artistiques de ce tapis et a faire la",
    "démonstration de ce qui le singularise",
    "aux autres tapis marocains. Mais avant",
    "de passer a la présentation du tapis",
    "proprement dit, il les serait utile",
    "de rappeler conditions géographiques,",
    "socio-économiques et culturelles dans",
    "lesquelles il est produit.",
    " ",
    "    Le tissage du tapis a Fes sur des",
    "bases organisées et en quantité, n'a",
    "commence qu'avec le début du 20eme",
    "siecle.",
    " ",
    "    Pour leur consommation les",
    "familles utilisaient des tapis",
    "produits localement, aussi bien que",
    "des tapis de Rabat ou en provenance",
    "extérieure, Dés sa fondation, Fes",
    "avait entretenu des relations",
    "commerciales avec des pays lointains",
    "produisant un artisanat de luxe",
    "(broderie, soieries, passementerie...).",
    " ",
    "    A Fas, les tisseuses ne semblent"
    "pas s'etre intéressées",
    "particuliarement au tissaqe des tapis",
    "dans le passé. La production du tapis",
    "a Fes a évolué a travers trois étapes",
    "importantes caractérisant ainsi le",
    "tissage dans cette ville.",
    " ",
    "    Dans les on comptait deux",
    "fabriques de tapis importantes (dont",
    "la Maquina, atelier géant, fabrique",
    "d' armes (photo 5). Déja a cette",
    "époquej les tapis réalisés étaient",
    "une reproduction de tapis de Rabat,",
    "ceci pour répondre, essentiellement,",
    "une demande locale croissante.",
    " ",
    "    Le nombre d'ateliers créés ira en",
    "augmentant pour faire face a la",
    "demande croissante du marché francais,",
    "surtout apres le succes suscité par",
    "les tapis marocains a l'exposition",
    "artisanale orqanisée a Paris en 1917.",
    " ",
    "    La commercialisation du type de",
    "tapis produits connaissalt un grand",
    "succes. Ainsi, en 1962, il n'existalt",
    "a Fas, pour la production des tapis",
    "qu'un seul atelier et une coopérative",
    "de production d'emploi relativement",
    "faible par rapport a Ia situation",
    "antécédente.",
    " ",
    "    Les choses ne vont commencer a",
    "changer qu'a partir de la fin de la",
    "décennie 1970 et début des années",
    "1980.",
    " ",
    "    A partir de cette période, on",
    "assiste a l'apparition de modéles de",
    "création locale faisant référence au",
    "décor des charpentes en bois, et aux",
    "trames géométriques du Zellige de Fes.",
    " ",
    "    Par ailleurs, Fes adapte a son",
    "qout aussi bien le tapis Rabat que",
    "des modéles de tissaqe de différents",
    "horizons. Enfin, Fes semble",
    "actuellement se spécialiser dans la",
    "production de tapis fins etaà motifs",
    "complexes. Le serraqe des tapis de",
    "Fes étant aujourd'hui un des plus",
    "élevés du Maroc, atteignant parfois",
    "50 nceuds au décimetre linéaire et",
    "parfois rnerne plus, Un telle finesse",
    "nécessite l'usage des nceuds qui",
    "prennent moins de place lorsqu'ils",
    "sont montés sur les paires de fils de",
    "chaine, c'est pour cela que les",
    "tisseuses de Fes utilisent la",
    "technique du nceud dit sehna, Cette",
    "technique est inspirée de celle du",
    "nceud persan qui porte d'ailleurs la",
    "meme dénomination (dessin 4). La",
    "production a lieu, aussi bien dans",
    "les ateliers d'enverqure, de plus en",
    "plus importants, que dans des",
    "ateliers plus modestas appartenant a",
    "des tisseuses ou anciennes maalmates.",
    " ",
    "    Pour la production des motifs,",
    "les tisseuses de Fes utilisent des",
    "plans et des mises en carte",
    "minutieusement établis (dessin 5).",
    " ",
    "    Lélaboration des plans ne se",
    "limite pas Généralement a une simple",
    "reproduction, mais elle peut inclure,",
    "exclure ou remplacer les éléments de",
    "décor puisés dans le répertoire des",
    "motifs traditionnels marocains. De la",
    "réussite du theme dépendra, alors, la",
    "valeur artistique du tapis produit",
    "qui peut prendre l'allure d'un",
    "chef-d'ceuvre, C'est cette qualité",
    "que revendiquent les tisseuses de Fes",
    "paur leur compte."
]