textList = [
   "   Outre la légende connue de toutes les tisseuses chevronnées de",
   "Rabat, se rapportant à la légende de la cigogne (un jour que les",
   "cigognes venaient, comme chaque année en janvier, de réapparaítre",
   "dans le ciel de Rabat, l'une d'elles, après avoir longuement plané",
   "au-dessus du l'une des maisons de la médina, laissa tomber dans le",
   "patio aux de cette habitation un fragment de tapis, après quoi qu'elle",
   "bati son nid sur un angle de la terrasse. Le fragment en question, d'un",
   "coloris et d'un décor jusque-là inconnu dans le pays, intrigua fort les",
   "tisseuses de la maison qui, y voyant à la fois un don du ciel, un porte",
   "bonheur et un heureux présage, s'en inspirent. C'est ainsi, dit la",
   "légende, que naquit le tapis de Rabat. Les tisseuses ont battít un des",
   "motifs de décor pied de cigogne (photo 16).",
   " ",
   "   La tradition attribue également la création du tapis de Rabat à",
   "deux jeunes filles considérées par la suite comme des saintes par la",
   'sagesse populaire: "Lalla Oum Knabech" et "Lalla Zineb" "Lahdia".',
   " ",
   "   Au sujet de la première, les mères racontaient à leurs petites",
   "filles que la sainte femme commençait un tapis le matin et le",
   "terminait le soir.",
   " ",
   "   Quant à la deuxième, on raconte qu'elle filait le jour et tissait",
   "la nuit. Les jeunes filles qui désoraient acquérir une grande habileté",
   "des doigts, se rendaient d'abord au sanctuaire de la première sainte;",
   "là, elles mangeaient sept raisins secs et buvaient une gorgée de lait",
   "dans lequel on faisait tremper un flocon de laine prélevé sur un tapis",
   "en cours d'exécution. Aprés, elles formulaient des vceux et priaient:",
   '"Lalla Oum Knabech, apprends-moi les secrets du tapis, montre-moi',
   'le sentier de la compréhension, conduis-moi dans le bon chemin".',
   " ",
   "   Elles se dirigeaient ensuite vers la tombe de la seconde, allumaient",
   'un cierge et disaient: "Lalla Zineb, je voudrais tisser un joli tapis;',
   'inspire-moi, dirige mes doigts adin que mon tapis soit le plus beau".',
   " ",
   "   D'autres tisseuses racontent qu'une troisième sainte, Lalla Touhamia,",
   "travallait à la lueur des étoiles et avait composé maints motifs , entre",
   "autres: Kronfla (Girofle), m'habka (le bouquet), chejra (arbre). Les",
   "jeunes filles qui voulaient leur tapis bien décoré, se rendaient sur sa",
   "tombe qu'elles honoraient par des fumigations en faisant le tour sept",
   "fois, répétant: Lalla Touhamia, initie-moi à l'art du décor pour que",
   "mon tapis soit comme un arbre fleuri; si je réussis, je brulerai",
   "pour toi deux cierges.",
   " ",
   "   D'autres légendes, précieusement préservées par des tisseuses,",
   "enrichissaient la culture populaire, Elles se racontent souvent autour",
   "des métiers et visent essentiellement à stimuler l'esprit des enfants,",
   "à les attirer vers des personnages mystiques, modèles de vertu et de",
   "qualités humaines, Lorsqu'une apprentie parvenait au rang de maalma",
   "(maítresse), la coutume voulait qu'elle offre, à celle qui l'avait",
   "initiée, un caftan et une sebniya (foulard de soie); c'était aussi",
   "l'occasion d'une fête ou maalma, amies, ouvrières et apprenties étaient",
   "conviées.",
   " ",
   "   Aussi bien dans le monde citadin que rural, la laine est considérée",
   "comme un don du ciel; c'est produit du Dieu, vénéré par toutes les",
   "tisseuses. Quel textile noble et bénéfique est la laine. Les vertus que",
   "lui prêtent encore aujourd'hui des tisseuses sont restées intactes. La",
   "laine est blanche, couleur de bon augure. Ses charmes sont puissants car",
   "un flocon passé dans la coiffe suffit à assurer la protection de la",
   "fileuse; ...Un brin de laine noué à la pate du mulet ou de la jument,",
   "ou à la queue de la vache qu'on vient d'acheter, attire sur eux la",
   "bénédiction, ...Le matin du mariage, autour du doigt de la mariée, on",
   "enroule ainsi la laine que le marié le soir déroulera.",
   " ",
   "   Il y a aussi beaucoup de mystères dans la laine, puisque de toison",
   "elle devient fil (photo 17), et de fils vêtement, couverture ou coussin.",
   " ",
   "   La laine enfin peut devenir tapis, et c'est là un nouveau mystère:",
   "des centaines de milliers de petits nceuds, surajoutés un à un, en bonne",
   "grace, sur le fond du tissu, s'ordonnent selon une esquisse seulernent",
   "imaginée dans le mental des tisseuses, jamais matériellement figuré,",
   "pour former un ensemble aux couleurs et lignes toujours parfaitement",
   "équilibrées et qui parviennent à exercer un charme qui peut conduire",
   "jusqu'à l'émerveillement (photo 18).",
   " ",
   "   La préparation pour le montage ou la confection du premier tapis de",
   "la nouvelle tisseuse était entourée de certains rites; d'abord la mere",
   "de la tisseuse placait quelques pieces de monnaie, (pour attirer les",
   "bonnes influentes), pres des deux piquets plantés par terre servant",
   "d'ourdissoir pour préparer les fils de chaine. Durant le va-et-vient de",
   "la jeune tisseuse entre les deux piquets (photo 19), on poussait des",
   "youyous, on frappait du tambourin, on offrait aux assistantes du lait",
   "et des dattes. Des cierges étaient allumés de part et d'autres des deux",
   "montants du métier. On brulait des aromates. Au haut du métier, on",
   "accrochait une amulette contre le mauvais ceil, un mouchoir rempli de",
   "laine, une gousse de cinq feves ou, un fer a cheval, un petit sachet en",
   "tissu contenant un peu d'alun, du benjoin et du harmala (photo 20).",
   " ",
   "   La tisseuse ne doit commencer son tapis que le corps purifié, il",
   "s'aqit d'un soin particulier que l'on doit apporter a son travail, Taute",
   "femme récemrnent répudiée, ou ayant ses regles ou encore jeune veuve,",
   "ne doit pas entrer chez une tisseuse, car elle arnenera avec elle la",
   "malédiction qui exercera un effet néfaste sur la tisseuse, le tapis et",
   "sur le foyer. Quand Ia femme prépare les teintures (photo 21), elle doit",
   "etre en état de pureté corporelle, sinon sa teinture se décomposera.",
   " ",
   "   Au Maroc, dans les plus humbles maisons des montagnes, la maitresse",
   "de maison possede un métier a tisser qui est composé de deux rouleaux",
   "(ensouples) soutenus par deux montants et une corniche simple, coupés",
   "par un artisan dans les petits troncs arbres. Le rouleau supérieur porte",
   "le nom du ciel, celui du bas représente la terre: ainsi, pour la tisseuse",
   "de tapis, quatre pieces en bois sont suffisantes pour symboliser",
   "l'univers (photo 22).",
   " ",
   "   Quand les femmes montent le métier, elles offrent aux passants et",
   "voisines venues pour aider, quelques fruits secs tels que: amandes,",
   "dattes et figues. Il s'aqlt de la meme offre qui précede et accompaqne",
   "le mariaqe. En effet, il est question de mariaqe entre les deux rouleaux",
   "placés sous le signe des noces entre le ciel et la terre (photo 23).",
   " ",
   "   Le travail du tissage est un travail de création, un accouchement.",
   "Une fois que le produit fabriqué et terminé, la femme coupe les fils qui",
   "le retiennent au métier, et ce faisant, elle prononce la meme formule",
   "de bénédiction que prononce la sage-femme en coupant le cordon",
   "ombilical du nouveau-né.",
   " ",
   "   Si chez certaines tribus, le tapis fini et détaché du métier est",
   "identifié a un enfant qui vient de naitre, pour d'autres populations, la",
   "meme opération est associée a la mort, Les tisseuses chantent alars une",
   "chanson. La meme chanson est chantée par les moissonneurs apres la",
   "moisson, La chanson est la suivante: Meurs, meurs notre champa Gloire",
   "a celul qui ne meurt jamas, notre Seigneur peut te donner la vie"
]