textList = [
    "    Beaucoup plus fruste, le tapis du mayen Atlas, encare appelé tapis",
    "berbêre est le tapis spécifique à un certain nombre de tribus. Mais",
    "encare, aucune légende n'en rappelle l'apparition. Fabriqué depuis des",
    "temps immémoriãux, la plupart de ses motifs existent déjà dans maintes",
    "mosalques romaines et byzantines, Il peut être considéré comme",
    "véritablement autochtone.",
    " ",
    "    «Tazrbit», c'est le norn qu'on donne au tapis dans le Haut Atlas.",
    "Dans le 'bel Siroua, ce massif volcanique qui relie le grand Atlas à",
    "l'anti-Atlas, en direction des qrands espaces sahariens, le tapis",
    "«Ouzguitl» accuse des formules décoratives, plus diversifiées que",
    "celles du tapis du moven Atlas, mais toujours strictement qéométriques,",
    "ainsi qu'un coloris plus brillant dü à l'utilisation de Ia Iaine du",
    "pays au fibras peut vrillées et soyeuses, comme du poil.",
    " ",
    "    Enfin, dans le Haouz de Marrakech, le tapis des «Oulad Bousebaâ»",
    "appelé par les commerçants tapis de «Chichaoua», se différencie des",
    "précédents par un -grand champ uniforme rouge tres soutenu soit uni,",
    "soit plus ou mains couvert de motifs. Ce genre de tapis qui utilise",
    "exclusivement comme fils de chaine des fils filés à base de poils de",
    "chêvre et de fibres de Iaine naires.",
    " ",
    "    Les tapis du monde rural marocain n'obéissent à aucune regle pour",
    "ce qui est de la maniére dont ils sont tissés et noués, On y trouve",
    "l'usage des dans les tapis du Haut Atlas, avec le tissage d'une",
    "lisiêre tres particuliêre (voir dessin 7). Pour les tapis du Moven",
    "Atlas, Timprovisation n'a pas de limite, mais ici on trouve le nceud",
    "qu'on peut qualifier de maracain (voir dessin 8), c'est le nceud",
    "berbêre (voir photo 15). Ce nceud peut être exécuté sur deux fils ou",
    "sur quatre fils de chaine (voir dessin 9), Les tapis des Oulad",
    "Bousebaâ, sant connus par l'usage d'une lisiêre tissée en dents de",
    "scie (voir dessin 10)."
]