textList = [
    "    Jadis lorsqu'on parlait de la",
    "production de l'artisanat des tapis",
    "dans la ville de Rabat (photo1), en",
    "faisait allusion d'une maniére tacite",
    "a celle de la ville de Salé. Si",
    "actuellement on ne trouve à Rabat",
    "que quelques coopératives qui",
    "oeuvrent encore dans le domaine de",
    "la production des tapis, Salé",
    "conserve encore et pleinernent sa",
    "renomrnée en tant que centre de",
    "production de tapis citadins. Partout",
    "dans les ruelles étroites de",
    "l'ancienne médina de Salé, on entend",
    "battre encore les peiqnes qui",
    "entassent et duites selon une mélodie",
    "continuellement répétée.",
    " ",
    "    Les anciens tapis de Rabat qui",
    "embellissent aujourd'hui encore",
    "certains musées nationaux sont plus",
    "longilignes et étroits. Les dimensions",
    "de ces tapis sont une conséquence",
    "directe imposée par remplacement ou",
    "ils sont destinés. En effet, les",
    "anciennes demeures construites jadis",
    "selon une architecture andalouse",
    "étaient datées de chambres ou de",
    "pieces plus longues et étroites, ce",
    "qui laissait un espace a couvrir avec",
    "les tapis ne dépassant pas 1.5 a 2",
    "metres de largeur.",
    " ",
    "    Comme cest aussl le cas pour a",
    "plupart tissus, tout tapis est",
    "compasé des fils de chaina qui en",
    "constituent le squelette, Ceux-ci",
    "sont régulierement entrecroisés avec",
    "des fils de trame (dessin1).",
    "Toutefois, la moquette ou le velours",
    "du tapis, résulte de la juxtaposition",
    "des nceuds, Les nceuds sont montés,",
    "les uns a coté des autres, sur des",
    "paires de fils de chaine successives",
    "selon une méthode turque appelée",
    "ghhiordés, Au Maroc, elle porte",
    "également l'appellation nceud.",
    "R'batI (dessin1) (photo2). Apres",
    "nouage de chaque rangée de rcuds,",
    "deux fils de trame sont ensuite",
    "tissés, et ainsi se succêdent des",
    "rangées de nceuds et des ranqées",
    "de paire de trame jusqu'a",
    "l'achevement du tapis (dessin3),",
    "Le résultat est l'aménagement sur",
    "Ilune des faces du tissu d'une",
    "sorte de velours ou de moquette,",
    "caractéristique du tapis.",
    " ",
    "    Le degré de finesse d'un tapis",
    "dépend naturellement du degré de",
    "finesse de ses compasants :",
    "moquette, fils de chaine et fils",
    "de trame, Conséquence pour une",
    "meme surface : plus un tapis est",
    "fin, plus la confection exige",
    "dépenses et temps additionnels.",
    " ",
    "    Cest ainsi que lion distingue",
    "quatre catégories des tapis de Rabat",
    "a savoir:",
    " ",
    "    - Les tapié de quallté courante:",
    "ceux-ci comptent au moins 50.000",
    "nceuds au m2; soit environ 22 nceuds",
    "par décimetre linéaire.",
    " ",
    "    - Les tapis de quanté moyenne:",
    "ils comptent au moins 70.000 nceuds",
    "au m2, soit environ 26 nceuds par",
    "décimetre linéaire.",
    " ",
    "    - Les tapis de qualité",
    "supérrieure: ils comptent au moins",
    "90.000nceuds au m2, soit enviran",
    "30 nceuds par décimetre linéaire.",
    " ",
    "    - Les tapis de qualité extra",
    "supérieure: ils comptent au mains",
    "160.000 nceuds au m2, soit environ",
    "40 nceuds par décimatre linéaire.",
    " ",
    "    La surface du tapis, caté",
    "moquette se compase des petits",
    "points qui constituent les éléments",
    "de dessin. En effet, chaque nceud",
    "laisse voir deux petits bouts sur",
    "la surface velours du tapis.",
    "L'espace occupé par un nceud est",
    "d'environ 3 mm sur 5mm. Cela dit,",
    "pour éclairer les amateurs sur",
    "l'un des moyens d'appréciation de",
    "la valeur des tapis, indépendamment",
    "d'autres éléments tel que la",
    "qualité de la matiere premiere et",
    "de la teinture, ou encore l'intéret",
    "du décor et du coloris, Le serrage,",
    "c'est-a-dire le nombre de nceuds",
    "par unité de surface, compte d'une",
    "maniére déterminante pour la valeur",
    "du tapis, Plus un tapis est fin,",
    "plus il comprend un nombre tres",
    "élevé de nceuds et par conséquent",
    "plus de temps pour sa confection."
]