textList = [
   "   A travers l'histoire, les marocains ont été toujours porté de par ",
   "leur nature reveuse et contemplative, a s'exprimer dans des formes",
   "diart spontanées. Ils ont conservé, a travers les bouleversements",
   "successifs d'une histoire mouvementée, beaucoup de leurs qualités",
   "primitives, qui se manifestent dans les arts manuels de facon souvent",
   "insurpassable, Les ceuvres exposées dans les divers musées a travers",
   "le Maroc laissent découvrir un art qui puise son origine dans le",
   "comportement quotidien, et s'inspire d'une conception purement",
   "spontanée de la vie sociale et patfois théocratique, dans laquelle se",
   "confondent le divin et l'humain.",
   " ",
   "   Dans l'expression de l'ame marocaine, l'art du tapis demeure l'un",
   "des témoiqnages les plus privilégiés et les plus authentiques de la",
   "recherche du beau. Il serait tres prétentieux d'essayer de fixer la",
   "date de l'apparition des tapis au Maroc, car celle-ci est considérée",
   "comme une évolution du tissage dant les origines remontent",
   "indéniablement a la préhistoire. Si des historiens attribuent",
   "l'apparition du tissaqe aux Eqyptiens, aux Indous, aux Assyriens, Aux",
   "Incas... le plus plausible est que cet art tradition est apparu dans",
   "une meme époque et dans des endroits différents du globe. On ne peut",
   "supposer alors qu'une chose, c'est que l'histoire du tissaqe est aussi",
   "ancienne que l'histoire du Maroc meme.",
   "",
   "   Ibn Khaldoun, dans ses proléqomenes, rédiqés a la fin du quatorziame",
   "siacle, évoque maintes fois dans l'esprit particulier au monde",
   "islamique, les métiers qui se pratiquaient en son temps, notamment le",
   "tissaqe d'étoffe qu'il traite en cinq lignes sans faire la moindre",
   "allusion au tapis. Serait-ce que les Villes ignoraient ce genre de",
   "fabrication? Serait-ce parce que le cloisonnement des centres",
   "commerciaux et les difficultés de transport empechaient Ia diffusion",
   "du tapis?",
   " ",
   "   On peut dire avec précaution également que l'artisanat tribal, en",
   "général, n'attirait pas l'attention des historiens.",
   " "
   "   De toutes les facons, aucun des auteurs, meme les plus connus qui",
   "ont écrit sur l'histoire du Maroc, notamment Al Murrakoshi dans Al",
   "Mouajib, Ibn Abi Zira dans Rawd Al Kirtas, Al Egzennay dans Zahrat",
   "Al As ou l'auteur anonyme de la Dakirat Attaniya n'ont parlé du",
   "tapis, Et il est également possible que certains écrits soient perdus",
   "ou soient encore enfouis dans quelques bibliotheques.",
   " "
   "   Il faut attendre la fin du dix neuvieme siêcle et le début du",
   "vingtieme pour que les littératures étrangeres (francaise, allemande",
   "et meme anglaise) commencent a découvrir le tapis marocain, a en",
   "définir les différents genres, indiquer les lieux de production, sans",
   "aborder toutefois l'essentiel, à savoir son histoire. Il faut",
   "reconnaitre que la résistance berbêre, à nliinstallation du protectorat,",
   "jusqu'en 1933, rendait toute recherche tres délicate.",
   " ",
   "   Malgré cette abondance littéraire, des lacunes existent et de",
   "nombreuses questions restent sans réponse.",
   " ",
   "   Si llorigine du tapis citadin souleve encore des controverses,",
   "liunanimité se fait autour du tapis bédouin en tant que tapis marocain",
   "authentique, Ceux de Rabat, Médiouna et Casablanca posent encore un",
   "certain nombre de questions.",
   " ",
   "   Alors que les deux derniers sont inspirés du tapis de Rabat, le",
   "livre u Arts et objets du Maroc souligne, a propos d'un tapis de",
   "Médiouna, Y..que les motifs et la composition du décor sont dans la",
   "plus pure tradition espagnole du seizlérne siecle D'autres auteurs",
   "affirment que le tapis espagnol du 16eme siecle est inspiré de liart",
   "arabe ou turco-persan.",
   " ",
   "   Quant au tapis r'bati, selon les uns, il serait venu d'Andalousie,",
   "parmi les souvenirs précieux emportés par les Gharnatis expulsás",
   "d'Espagne, a la fin du 15eme siecle et qui se sont fixés a Rabat, Fas",
   "et Tétouan. C'est Ia these que soutiennent les notables éclairés de",
   "Rabat, pour la plupart descendants authentiques des Gharnatis. Une",
   "telle position est justifiable si l'on tient compte de la proximité de",
   "la Péninsule Ibérique et des liens qui ont toujours uni les deux",
   "communautés.",
   " ",
   "   Mais d'apres Prosper Ricard, qui se base sur la comparaison des",
   "tapis de Rabat avec ceux d'Asie Mineure (Anatolie et Perse) étudiés",
   "par des chercheurs allemands et anglais, et suite aux rapprochernents",
   "qu'il fait quant a l'encadrement, aux couleurs et meme aux motifs,",
   "l'auteur du Corpus des Tapis Marocains soutient que le tapis de",
   "Rabat aurait été introduit au Maroc par les Turcs, au 18eme siacle,",
   "lors de leur occupation de l'Algérie.",
   " ",
   "   Quoi qu'il en soit, un fait est certain; le tapis se confectionnait",
   "déja sur les bords du Bouregreg au 18eme siecle: un tapis dit de",
   "Chiadma porte la date tissée, 1202 hégirienne, soit1798 (photo a).",
   " ",
   "   Dans l'attente des résultats de la recherche, on ne trouve, pour le",
   "moment que cinq passages relatifs au tapis dont trois sont citás par",
   "P. Ricard:",
   " ",
   "   1) L'auteur du Corpus souligne dans Tapis marocains que l'histoire",
   "rappotte que le Sultan Moulay El Hassan, voulant remercier les chefs",
   "d'Etats européens de leurs félicitations a l'occasion de son accession",
   "au trane du Maroc, leur envoya une ambassade chargée de présents",
   "destinés au Président de la République française Mac Mahon, aux rais",
   "de Belgique et d'ltalie, Léopold II et Victor Emmanuel Il, ainsi qu'a",
   "la reine d'Angleterre Victoria. Les chefs d'Etats de ces pays recurent,",
   "entre autres objets, chacun Six tapis de Rabat, tandis que leurs Chefs",
   "de Gouvernement et leurs Ministres des Affaires Etrangeres en recurent",
   "deux chacun.",
   "",
   "   De son caté, Abou Abbes Naciri, dans son ouvrage Al Istiqssa, écrit",
   "a la fin du regne de Moulay El Hassan Premier et parle de présents",
   "offerts aux mêmes chefs d'Etat, Il cite la délégation qui les",
   "accompagna, présidée par l'ambassadeur Si Mohamed Ben Tahar Zebdi, de",
   "Rabat,",
   " ",
   "   2) Commentant un tapis de Rabat, Prosper Ricard écrit: Ce tapis fit",
   "partie jusqu'en 1907 du mobilier d'un membre de la famille chérifienne,",
   "Moulay Rachid, (cousin de l'ex-sultan Moulay Hafid). Il fut fabriqué,",
   "dit-on, vers 1858, sur ordre du sultan Moulay Abderrahmane (1822-1859),",
   "par les soins d'Al Adnani",
   " ",
   "   3) Le troisieme point concerne la révélation de la date dexécutio",
   "d'un tapis de Chiadma (ou de Rabat) : 1202 hégirienne, soit1798.",
   
   "   4) A propos du commerce marocain avec la France, durant les années",
   "1860-1866, Jean Louis Miege écrit : La valeur des tissus de Iaine et",
   "des tapis exportés est de 350.000 à 55Cl.ClClCl francs par an. Un fort",
   "accroissement caractérise ces ventes en 1863.",
   " ",
   "   S) Quant à la cinquiàme citation, dest Mohammed Ben Hassan Al",
   "Ouazzan, dit Léon l'Aricain qui ecrit, au début du 16me siecle,",
   "parlant de la Kissaria de Fes : ' Pres de la, dans quelques petites",
   "boutiques, on vend aux enchàres des tapis et des couvre-lits.",
   " ",
   "   L'industrie du tapis ne s'est guere développée a Fes, comme dans",
   "d'autres Villes malqré la présence de l'élément Gharnati.",
]