textList = [
    "    Le Maroc rural est synonyrne de chaleur et d'hospitalité, Le plus",
    "modeste des campaqnards voUs offrira toujours un verre de thé a la",
    "menthe, Les paysans agriculteurs ou artisans sont aussi des artistes",
    "qui savent s'exprirner dans la poésie et la musique, Le chant et la",
    "danse font partie des traditions rurales. Ces artistes savent",
    "également s'exprimer à travers toute sorte d'objet qu'il soit a",
    "caractere utilitaire ou décoratif.",
    " ",
    "    L'art traditionnel marocain se manifeste d'une facon évidente dans",
    "les objets issus du monde rural; le tissaqe en est un des exemples les",
    "plus éloquents, Qu'il soit issu des tribus nomades ou sédentaires, le",
    "tissage utilise la surface du tapis comme support d'expression pour",
    "mettre en évidence des qualités de création artistique remarquables.",
    "Les tapis tissés peuvent etre considérés comme des oeuvres dart",
    "plastique.",
    " ",
    "    Les manifestations de l'art bédouin sont pouttant limitées a",
    "certains espaces. La vie est simple dans le monde rural et les besoins",
    "y sont restreints. En dehors de l'habitat, le bédouin n'a quere a se",
    "préoccuper que du couchaqe, du vêtement, de la confection de quelques",
    "appareils agricoles et de transport, d'ustensiles pour la conservation",
    "des provisions et pour la préparation des aliments.",
    " ",
    "    Quand le bédouin est nomade, tout son équipement est rudimentaire:",
    "le déplacernent continuel des tribus pour la transhumance rejette tout",
    "encornbrement et s'oppose aux travaux de longue haleine nécessitant un",
    "outillaqe fragile ou tres perfectionné.",
    " ",
    "    Dans l'art des tapis ruraux, on se rend compte que, de la diversité",
    "des motifs découlent des compositions qui ne répondent pas a une",
    "technique préconçue. On peut considérer que la symbiose d'une telle",
    "variété de motifs hétérogênes n'est que le fondement diun art naif",
    "inné, sans regles nilois, et qui puise ses ressources dans",
    "l'épanouissement de l'imaginaire des tisseuses.",
    " ",
    "    Les tapis ruraux présentent parmi leurs motifs de base:",
    " ",
    "    - le trait",
    " ",
    "    - le carré",
    " ",
    "    - le losange",
    " ",
    "    - le triangle",
    " ",
    "    (dessin 6)",
    " ",
    "    Il est tres difficile de remonter l'histoire pour parler des",
    "origines de l'art rural marocain dans la mesure ou il n'y a pas de",
    "référence fiable; l'art populaire est lui-même énigmatique,",
    "l'influence de l'lslam ne pouvant pas être prise en compte comme",
    "source, car cet art existe avant la conquete islamique, D'ailleurs,",
    "il est en apparence sans origine scripturaire évidente dans la mesure",
    "ou le tifinakh ne nous ait oas encore révélé tous ses secrets.",
]